apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubenotes
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/kubenotes
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
